Multipatch coefs
gismo/gismo pull request #597
Opened 2023-03-27 09:10 UTC by hverhelst

Adds gsMultiPatch::coefs()

**Please consider the following checklist before issuing a pull
request:**
- [x] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [x] Have you documented any new codes using Doxygen comments?
- [x] Have you written new tests or examples for your changes?
-----

2023-03-31 14:51 UTC, stefantakacs requested changes, later dismissed

2023-03-31 14:51 UTC, stefantakacs commented on src/gsCore/gsMultiPatch.h
> +        }
offset += (*it)->coefsSize();

Pls. verify that the function actually works as intended.

2023-04-08 07:04 UTC, hverhelst commented on src/gsCore/gsMultiPatch.h
> +        }
Thanks @stefantakacs , this was a sloppy copy-paste... I have fixed it.

2023-04-21 08:22 UTC, filiatra approved these changes

2023-04-21 15:36 UTC, filiatra approved these changes

2023-04-24 21:45 UTC, merged