Barrier clean
gismo/gismo pull request #624
Opened 2023-06-29 09:36 UTC by jiyess

This branch features our construction of analysis-suitable parameterizations from input boundary representations, comprising the following five files:
- `gsAnalysisSuitableParameterization.cpp`: An example file demonstrating usage.
- `gsBarrierPatch.h`: Header file for the Barrier Patch class.
- `gsBarrierPatch.hpp`: Implementation file for the Barrier Patch class.
- `gsBarrierCore.h`: Header file for the Barrier Core class.
- `gsBarrierCore.hpp`: Implementation file for the Barrier Core class.

In the folder `/filedata/breps/`, we've included various test files for your convenience. Please note that redundant files in the `/filedata` folder have been cleared out to maintain cleanliness and organization.

Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.

Code submitted to the stable branch should be clean, well-documented
and free of bugs.

# Please consider the following checklist before issuing a pull
request:
- [v] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [v] Have you documented any new codes using Doxygen comments?
- [v] Have you written new tests or examples for your changes?
-----

2023-06-29 10:00 UTC, filiatra requested changes

2023-06-29 10:00 UTC, filiatra commented on CMakeLists.txt
> +if(GISMO_WITH_HLBFGS)
This is not needed, or at least it should not be needed.

2023-06-29 10:00 UTC, filiatra commented on examples/gsAnalysisSuitableParameterization.cpp
Please rename as 
an_parameterization_example.cpp

2023-06-29 10:00 UTC, filiatra commented on src/gsAssembler/gsExpressions.h
> +   Expression for the exponent of expression
rename as
exp_expression 

I think the more correct term is exponential

2023-06-29 10:00 UTC, filiatra commented on src/gsAssembler/gsExpressions.h
> +template<class E>
please add some words of documentation.

2023-06-29 13:16 UTC, hverhelst commented on src/gsModeling/gsBarrierPatch.h
> +#include <gsHLBFGS/gsHLBFGS.h>
Maybe you need
```
#ifdef gsHLBFGS_ENABLEDMaybe you need
```
#ifdef gsHLBFGS_ENABLED
#include <gsHLBFGS/gsHLBFGS.h>
#endif
```
but probably the include can be completely removed.
#include <gsHLBFGS/gsHLBFGS.h>
#endif
```
but probably the include can be completely removed.

2023-06-29 13:17 UTC, hverhelst commented on src/gsModeling/gsBarrierCore.h
> +#include <gsHLBFGS/gsHLBFGS.h>
Maybe you need
```
#ifdef gsHLBFGS_ENABLEDMaybe you need
```
#ifdef gsHLBFGS_ENABLED
#include <gsHLBFGS/gsHLBFGS.h>
#endif
```
but probably the include can be completely removed.
#include <gsHLBFGS/gsHLBFGS.h>
#endif
```
Also think about the case where HLBFGS is not loaded (e.g. use gradient-based algorithm)

2023-07-28 06:09 UTC, filiatra approved these changes

2023-07-28 13:18 UTC, merged