Base64 I/O for Paraview and XML
gismo/gismo pull request #634
Opened 2023-08-31 16:04 UTC by jzwar

# Motivation
Although I was aware of the gismo-PR #236, I saw that there has not been an update since 2018 and it also relies on an external library. Further, it only acted on the XML-files without support for Paraview exports.

The need to redo the implementation of this feature originated as we had fields with very small magnitudes, which is very tedious with fixed-point string conversion.

# Implementation
The implementation is based on [this](https://github.com/tataratat/bezman/blob/main/src/utils/base64.hpp), which I implemented as an interface to @j042's python library [splinepy](github.com/tatatarat/splinepy). It relied on `c++17` features, so adaptations were required, and further overloads for `gsMatrix` were added. The `ToVTK`-function was updated accordingly.

## Details
- [x] Moved functions related to `GoTools` into a separate file, although it seems to be used nowhere (?)
- [x] Added a new class of static functions only for base64 encoding and decoding
- [x] Added `base64` option to Paraview collection and added argument to `toVTK`
- [x] Updated some variable names to make code clearer, formatted modified sections 
- [x] XML I/O

# Complementary
I would add the following, should there be a demand for it:
- [ ] Tests for De/Encoding (they already exist, but I did not know where to put them)

2023-09-01 04:49 UTC, mmoelle1 commented
I think that adding base64 support for the knot vectors would be very good. We are planning to implement something similar to the `Geometry` tag to write solutions as native spline objects in XML. These solutions will often have many coefficients and hence benefit largely from base64 support.

2023-09-12 13:33 UTC, jzwar commented
> I think that adding base64 support for the knot vectors would be very good. We are planning to implement something similar to the `Geometry` tag to write solutions as native spline objects in XML. These solutions will often have many coefficients and hence benefit largely from base64 support.

Done and rebased

2024-03-06 12:15 UTC, filiatra commented
Very usefull !
Tests can go in a new file inside /unittests
Please set in cmake GISMO_BUILD_UNITTESTS=ON
to be able to compile (make unitttestss) and run (./bin/unittests) the unittests.

2024-03-10 15:15 UTC, jzwar commented
@filiatra As discussed, I looked into the structure date is currently written to file. Adding a flag to gsFileData will not be sufficient. Streaming a file into `gsFileData` calls the `put` function, which is non-member. So, as far as I can see, no trivial way to add format flags to the output of the children without changing the layout of every put function.

2024-03-25 10:57 UTC, filiatra commented
OK then let's go on with this one as it is and let the writing for later.

2024-03-25 10:59 UTC, filiatra requested changes

2024-03-25 10:59 UTC, filiatra commented on src/gsIO/gsXml.hpp
> +                   [](unsigned char c) { return std::tolower(c); });
Please use "::tolower" instead of "std::tolower" because some windows compiles like it better.

2024-03-25 10:59 UTC, filiatra commented on src/gsNurbs/gsKnotVector.hpp
> +                       [](unsigned char c) { return std::tolower(c); });
Please use "::tolower" instead of "std::tolower" because some windows compiles like it better.

2024-06-17 13:59 UTC, merged