Keep Sparsity Pattern (Mini-PR)
gismo/gismo pull request #635
Opened 2023-08-31 18:00 UTC by jzwar

# Motivation
When doing multiple assemblies (e.g. in a non-linear problem, or in an optimization), accessing the sparse matrix can be a bottleneck when using the expression assembler. Whenever the `clearMatrix()` command was called, the matrix was reinitialized and the sparsity pattern was deleted.

In this suggestion, the matrix is multiplied by zero whenever clearMatrix is called to avoid re-initialization. This is also made default behavior.

With OpenMP in my optimization, it was significantly faster.

2023-09-04 07:54 UTC, weinmueller commented
Hello, that is interesting. Good to know. Could you try it with `setZero()` instead of `*=0`? Maybe this is faster (and cleaner)?

2023-09-04 10:33 UTC, jzwar commented
> Hello, that is interesting. Good to know. Could you try it with `setZero()` instead of `*=0`? Maybe this is faster (and cleaner)?

Hi :) The function `setZero`, as implemented [here](https://github.com/gismo/gismo/blob/8475faa0d6b9affd5d06988adf8c18a75b4566c4/external/gsEigen/src/SparseCore/SparseMatrix.h#L253), will not reallocate memory, but (as I understand it) set the index list to zero, basically "forgetting" that a value is stored at said location. If the function is called, subsequent access to an arbitrary value in the matrix will result in a call of the insert function. That's why imo, it is not suited for this application. 

An alternative approach to multiplication by zero, would be:
``` c++
std::fill(m_matrix.valuePtr(),
                  m_matrix.valuePtr() + m_matrix.nonZeros(), 0.);
```

2023-09-04 15:20 UTC, weinmueller commented
> If the function is called, subsequent access to an arbitrary value in the matrix will result in a call of the insert function. That's why imo, it is not suited for this application.

Okay, so if I understand correctly, you want to keep the memory of the sparse matrix? And then you modify somewhere the matrix with coefRef() which leads to the fact that this is faster?

2023-09-04 17:10 UTC, filiatra requested changes

2023-09-04 17:10 UTC, filiatra commented on src/gsAssembler/gsExprAssembler.h
> +        if (0 == m_matrix.rows() || 0 == m_matrix.cols())
Please use 4-space identation

2023-09-06 14:03 UTC, jzwar commented
> > If the function is called, subsequent access to an arbitrary value in the matrix will result in a call of the insert function. That's why imo, it is not suited for this application.
> 
> Okay, so if I understand correctly, you want to keep the memory of the sparse matrix? And then you modify somewhere the matrix with coefRef() which leads to the fact that this is faster?

@weinmueller Not only the memory, but also the non-zero locations, i.e., the sparsity information. Basically, the indices are kept as matrix entries with the value `0`. 

If you call coeffRef() for a non-existing matrix entry, then `insert` will be called. From the [eigen documentation](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html#title22):
>Assuming memory has been appropriately reserved, this function performs a sorted insertion in O(1) if the elements of each inner vector are inserted in increasing inner index order, and in O(nnz_j) for a random insertion. 

As increasing inner-index order is not assured, that can be an expensive task (when I tested, this was most important for many-patch-geometries). Adding to that: When compiling with OpenMP, `insert` blocks the thread to ensure safe access to the matrix, which slows down the assembly significantly.

2023-09-06 14:07 UTC, mmoelle1 commented
If you allow me to comment on this. @filiatra and I started with some improvement of the assemblers in which we do exactly what @jzwar needs. First generate the sparsity pattern (sequentially) and then do the assembly (with OpenMP parallelisation and `atomic` updates). For that we implemented some special version of the `coefRef()` that throws an error of the position is not available. The normal `coefRef()` would insert it, I guess. It's not yet in stable but will be soon, I hope.

2023-09-06 15:01 UTC, jzwar commented
> If you allow me to comment on this. @filiatra and I started with some improvement of the assemblers in which we do exactly what @jzwar needs. First generate the sparsity pattern (sequentially) and then do the assembly (with OpenMP parallelisation and `atomic` updates). For that we implemented some special version of the `coefRef()` that throws an error of the position is not available. The normal `coefRef()` would insert it, I guess. It's not yet in stable but will be soon, I hope.

@mmoelle1 I have been playing around with `setFromTriplets` for the same reason, which also helped to improve assembly times by quite a bit. Do you already have a plan to store the sparsity information? In that case, this PR would be redundant and I could close it. Otherwise, would you prefer the `std::fill` approach or rather `*=0.`?

2023-09-07 14:31 UTC, filiatra approved these changes

2023-09-07 14:35 UTC, filiatra commented
Please add a commit description using the keyword IMPROVED before mergins, eg:

IMPROVED: avoid re-initialization of .....


Regarding the comment of Matthias, I think that this PR is combatible with what we want to achieve, so in my opinion it can be mearged

2023-09-11 10:19 UTC, jzwar commented
> Please add a commit description using the keyword IMPROVED before mergins, eg:
> 
> IMPROVED: avoid re-initialization of .....
> 
> Regarding the comment of Matthias, I think that this PR is combatible with what we want to achieve, so in my opinion it can be mearged

@filiatra I am not authorized to merge myself, the merge button is greyed out.

2023-09-11 12:50 UTC, merged