fix linker error: undefined reference
gismo/gismo pull request #707
Opened 2024-05-08 15:02 UTC by AndreaBressan

FIXED: the combineMappers templated function with real_t was not instantiated in the library causing linker errors

instantiating revealed a different error that is also fixed

FIXED: an error in the combineMappers templated function that called copyBlockTo passing a matrix instead of a gsWeightMapper

2024-05-16 17:35 UTC, hverhelst requested changes

2024-05-16 17:35 UTC, hverhelst commented on src/gsMSplines/gsWeightMapper_.cpp
> +    index_t reorderMapperTarget (gsWeightMapper<real_t> &mapper, const std::vector<index_t>& permutation, gsPermutationMatrix* permMatrix=NULL);
Windows does not like the default argument here. Could you remove it?

2024-05-16 17:35 UTC, hverhelst commented on src/gsMSplines/gsWeightMapper_.cpp
> +    gsWeightMapper<real_t>* combineMappers (const std::vector<gsWeightMapper<real_t>*> &mappers, std::vector<index_t> &shifts, bool needShifting=true);
Same here, remove the default argument

2024-05-17 13:29 UTC, AndreaBressan commented on src/gsMSplines/gsWeightMapper_.cpp
> +    gsWeightMapper<real_t>* combineMappers (const std::vector<gsWeightMapper<real_t>*> &mappers, std::vector<index_t> &shifts, bool needShifting=true);
done

2024-05-17 13:44 UTC, hverhelst approved these changes

2024-06-07 09:55 UTC, merged