Small changes for basis, knot vector, domain iterator
gismo/gismo pull request #712
Opened 2024-05-16 17:38 UTC by hverhelst

NEW:
Paraview write for boxes represented by matrices 
Nestedness check of knot vector
Extra constructor for `gsTensorDomainBoundaryIterator` 

IMPROVED: 

FIXED:
ID of `gsTensorDomainIterator`

API:

----

Please consider the following checklist before issuing a pull
request:
- [X] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [X] Have you documented any new codes using Doxygen comments?
- [X] Have you written new tests or examples for your changes?
-----

2024-06-07 09:47 UTC, filiatra requested changes
There is the function:

gsBasisFun<T> function(index_t i) const

that can be used to get a handle on a single basis function.
This should do the same as "computesingle".

Can you tryto use that and if it works the same, remove computeSinge ?
it looks a bit of duplicated functionality.

2024-06-19 21:03 UTC, hverhelst commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR712](https://trello.com/c/7dCbOzSw/3-pr712)

2024-07-05 21:24 UTC, hverhelst commented
> There is the function:
> 
> gsBasisFun function(index_t i) const
> 
> that can be used to get a handle on a single basis function. This should do the same as "computesingle".
> 
> Can you tryto use that and if it works the same, remove computeSinge ? it looks a bit of duplicated functionality.

I have reverted the `computeSingle`. There is still the `evalAllDersDingle_into`, but that one provides an implementation of an existing function with that name using different input arguments.

2024-07-05 21:25 UTC, hverhelst reviewed
I have reverted the computeSingle. There is still the evalAllDersDingle_into, but that one provides an implementation of an existing function with that name using different input arguments.

2024-12-20 10:02 UTC, hverhelst commented
I have checked this PR again, @filiatra could you have a look.
One improvement would be to replace the `gsWriteParaview` function for boxes to a version where they are not written in `nBoxes` number of files, but instead just in one file (with an unstructured grid or so. I don't know yet which type to use in Paraview.

2025-01-03 09:28 UTC, filiatra approved these changes

2025-01-06 12:40 UTC, merged