Optim
gismo/gismo pull request #721
Opened 2024-07-07 09:51 UTC by hverhelst

Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.

Code submitted to the stable branch should be clean, well-documented
and free of bugs.

# The commit description must be structured as a list follows:

NEW: 
Add bindings to the [optim](https://github.com/kthohr/optim/) package

IMPROVED:

FIXED: 

API:
`gsOptProblem::numConstraints()` returned the number of lower bounds (which are box constraints). Now it returns the member `m_numConstraints` which is a user-defined flag. This keeps it functional for non-linear constraints, but the user has to set it explicitly.

-----
Please consider the following checklist before issuing a pull
request:
- [X] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [ ] Have you documented any new codes using Doxygen comments?
- [X] Have you written new tests or examples for your changes?
-----

2024-07-15 13:10 UTC, sofimp23 commented
If I include the optional submodule `gsOptim` via the `ccmake` interface, I get the following linking error:

> gismo/external/optim/header_only_version/misc/optim_options.hpp:221:10: fatal error: 'BaseMatrixOps/include/BaseMatrixOps.hpp' file not found #include "BaseMatrixOps/include/BaseMatrixOps.hpp"

and indeed `BaseMatrixOps` is empty.

If I include the optional submodule `gsOptim` via editing `../submodules.txt`, everything works.

Though, `BaseMatrixOps` is not moved into `optim/include`, but copied.
optim CMakeList.txt, line 28:
`file(RENAME ${gismo_externals}/BaseMatrixOps ${gismo_externals}/optim/include/BaseMatrixOps)`
From the CMake documentation:
> file(RENAME <oldname> <newname>)
> Move a file or directory within a filesystem from <oldname> to <newname>, replacing the destination atomically.

2024-07-19 15:27 UTC, filiatra commented
It should work now, please try it again.

2024-07-19 16:02 UTC, filiatra requested changes

2024-07-19 16:02 UTC, filiatra commented on optional/gsOptim/gsOptim_.cpp
> +#include <gsCore/gsTemplateTools.h>
No need for _cpp file, since all code is templated (inside .h file).

Actually this compiled code is never called in this scenario.

2024-08-01 16:48 UTC, filiatra approved these changes

2024-08-01 17:20 UTC, filiatra requested changes

2024-08-01 17:20 UTC, filiatra commented on CMakeLists.txt
> +# WHY IS THIS NEEDED HERE????
this should be removed. I think

2024-08-23 15:01 UTC, hverhelst commented
There is an issue when compiling `examples/optimizer_example.cpp`
```bash
In file included from gismo/external/optim/header_only_version/optim.hpp:24,
                 from gismo/optional/gsOptim/gsOptim.h:20,
                 from gismo/examples/optimizer_example.cpp:28:
gismo/external/optim/header_only_version/misc/optim_options.hpp:221:10: fatal error: BaseMatrixOps/include/BaseMatrixOps.hpp: No such file or directory
  221 | #include "BaseMatrixOps/include/BaseMatrixOps.hpp"
```
Whereas the file `gismo/optional/gsOptim/examples/optim_test.cpp` compiles fine (and uses the file `BaseMatrixOps/include/BaseMatrixOps.hpp`).

@filiatra or @jiyess could you have a look if there is something wrong in the [`CMakeLists.txt`](https://github.com/gismo/gismo/blob/6078c588cc3cd4c9c6a962eb42a6354777b9975e/optional/gsOptim/CMakeLists.txt)?

2024-09-09 11:37 UTC, filiatra approved these changes

2024-09-09 13:09 UTC, sofimp23 commented
The optimizer example does not compile for me.

`make optimizer_example` 

gives the following error:
```
gismo/external/optim/header_only_version/misc/optim_misc.hpp:25:10: fatal error: 'misc/optim_structs.hpp' file not found
#include "misc/optim_structs.hpp"
```

2024-09-16 15:56 UTC, merged