Implement Bezier Element export for ParaView
gismo/gismo pull request #740
Opened 2024-09-23 12:02 UTC by ckarampa

VTK (and subsequently ParaView) now natively supports Bezier elements. This allows us to export geometries ( and solution fields in a future PR) by means of Bezier extraction.

### NEW:
- `gsWriteParaviewBezier` accepts a `gsMultiPatch` and exports it as a *single* `.vtu` file containing `VTK_BEZIER_QUADRILATERAL` elements. Currently this is implemented only for bivariate geometries.
- `gsMultiPatch::BezierExtraction()` implements Bezier extraction via quasi interpolation and has been brought over from `gismo/gsLsDyna` and returns a multi patch consisting of all the bezier elements.. The struct `ElementBlock` and method `BezierOperator` are necessary for its  operation. The struct has been 'hidden' inside the `internal` namespace and `BezierOperator` has been marked private. 

### IMPROVED:
- Static functions of `gsParaviewDataSet` moved to a separate file, `gsParaviewUtils`. These deal mainly with formatting data to the .vtk format.
- `toDataArray` now also supports integers, matrices of integers, and custom xml tag attribute-value pairs.
- A flag has been added to `inputOutput_example`, which exports the geometry as bezier elements.
- `filedata/surfaces/teapot.xml` now contains a multi patch definition.

### FIXED:
### API:

### TODO:
- [ ] To avoid compilation errors the PR in `gismo/gsLsDyna` which deletes the struct/funtions from there needs to be accepted along with this PR.

# Please consider the following checklist before issuing a pull
request:
- [x] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [x] Have you documented any new codes using Doxygen comments?
- [x] Have you written new tests or examples for your changes?
-----

2024-10-17 10:50 UTC, filiatra requested changes

2024-10-17 10:50 UTC, filiatra commented on src/gsCore/gsMultiPatch.h
> +    gsMultiPatch<T> BezierExtraction() const;
rename as:
gsMultiPatch<T> extractBezier() const;

add one line of doxygen doc

2024-10-17 10:50 UTC, filiatra commented on src/gsCore/gsMultiPatch.hpp
> +        gsMatrix<real_t> newCoefs( ((ElBlock.PR+1) * (ElBlock.PS+1)), targetDim() );
newCoefs is not used ?

2024-10-17 10:50 UTC, filiatra commented on src/gsCore/gsMultiPatch.h
> +    std::map<index_t, internal::ElementBlock> BezierOperator() const;
add one line of doxygen doc

2024-10-17 10:50 UTC, filiatra commented on src/gsCore/gsMultiPatch.hpp
> +        gsKnotVector<T> kv1;
Make the basis creation using static dispatch here

2024-10-17 10:50 UTC, filiatra commented on src/gsCore/gsMultiPatch.hpp
> +        gsKnotVector<> kv1(0,1,0,ElBlock.PR+1);
Make the basis creation using static dispatch here as well

2024-10-17 10:50 UTC, filiatra commented on src/gsIO/gsParaviewUtils.cpp
> +        gsMatrix<real_t> T(nU*nV, nU*nV);
Rename the matrix T not to confuse with the template parameter

2024-10-17 10:50 UTC, filiatra commented on src/gsIO/gsParaviewUtils.h
> +    gsMatrix<real_t> vtkIDTransform(index_t nU, index_t nV);
needs GISMO_EXPORT attribute (Because it is not templated)

2024-10-17 10:50 UTC, filiatra commented on src/gsIO/gsParaviewUtils.h
> +
too many includes, they should move to the hpp file

2024-10-17 10:50 UTC, filiatra commented on src/gsIO/gsParaviewUtils.h
> +
needs GISMO_EXPORT

2024-10-24 07:35 UTC, ckarampa commented
In the `gsMultipatch::BezierOperator` we are grouping the `ElementBlocks` by `NN` i.e. the number of control points of each Bezier element. This will be problematic if in a multipatch there exist patches of different degree that have the same number of control points (e.g. 2x2 & 4x1). This might be rare but it is not impossible. We could group them by `(PR, PS, PT)` ( the degree per direction) to avoid this.

2024-11-04 14:28 UTC, ckarampa commented
> In the `gsMultipatch::BezierOperator` we are grouping the `ElementBlocks` by `NN` i.e. the number of control points of each Bezier element. This will be problematic if in a multipatch there exist patches of different degree that have the same number of control points (e.g. 2x2 & 4x1). This might be rare but it is not impossible. We could group them by `(PR, PS, PT)` ( the degree per direction) to avoid this.

I have implemented this locally, i.e. I do the grouping with respect to ( NNj, PRj, PSj, PTj). If we agree on this, I can commit it

2024-12-10 14:31 UTC, filiatra approved these changes

2024-12-10 14:32 UTC, merged