Introducing: Composite maps
gismo/gismo pull request #746
Opened 2024-12-03 10:41 UTC by hverhelst

**TO DO**:
- Check documentation @sofimp23 @jiyess @hverhelst 
- Add simple example for composite maps @sofimp23 @jiyess @hverhelst 

------

Add composite maps, via the classes `gsComposedBasis`, `gsComposedGeometry` and `gsComposedFunction`. They are relatively simple, but are fully integrated in the code, e.g., with XML support, and working with `gsExprAssembler`, `gsExprEvaluator` et cetera.

------
The commit description must be structured as a list follows:

NEW: 
`gsComposedBasis`, `gsComposedGeometry` and `gsComposedFunction`: the equivalents of `gsBasis`, `gsGeometry` and `gsFunction` taking a composition.
Add control parameters (named **controls** to avoid confusion with parameter space etc) and create accessors to them in `gsFunction`.
`gsFileData::hasLabel` to check if a file has an XML node with a certain label
Add extra tests for `gsReadFile`.

IMPROVED: 
Separate type for `gsXML<gsConstantFunction>`
Changed XML input for `gsFunctions` to a more generic way. Previously, only `gsFunctionExpr` and `gsConstantFunction` were supported. The read/write of those is moved to their own `hpp` files and `gsXml<gsFunction>` and `gsXml<gsFunctionSet` are added.

FIXED: 

API:

For each new/improved/fixed/api change use a new line with the
respective word prefix in capital.

-----
Please consider the following checklist before issuing a pull
request:
- [X] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [ ] Have you documented any new codes using Doxygen comments?
- [ ] Have you written new tests or examples for your changes?
-----

2025-01-05 11:21 UTC, sofimp23 commented on src/gsIO/gsXmlUtils.hpp
> +/// Get a FunctionSet from XML data
Get a Function

2025-01-05 11:24 UTC, sofimp23 approved these changes

2025-03-25 17:19 UTC, filiatra requested changes

2025-03-25 17:19 UTC, filiatra commented on src/gsCore/gsConstantFunction.h
> +#include <gsIO/gsXmlGenericUtils.hpp>
we cannot include a .hpp in an .h file.
We need to add .hpp and _.cpp for this...

2025-03-26 09:30 UTC, filiatra approved these changes

2025-03-26 12:36 UTC, merged