Merge precice_v3.0.0 into stable
gismo/gismo pull request #757
Opened 2024-12-13 08:41 UTC by Crazy-Rich-Meghan

Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.

Code submitted to the stable branch should be clean, well-documented
and free of bugs.

# The commit description must be structured as a list follows:

NEW: ...
IMPROVED: ...
FIXED: ...
API:...

For each new/improved/fixed/api change use a new line with the
respective word prefix in capital.

# Please consider the following checklist before issuing a pull
request:
- [ ] Have you added an explanation of what your changes do and why
  you'd like us to include them?
- [ ] Have you documented any new codes using Doxygen comments?
- [ ] Have you written new tests or examples for your changes?
-----

2024-12-20 10:33 UTC, hverhelst requested changes

2024-12-20 10:33 UTC, hverhelst commented on optional/gsStructuralAnalysis
Can you undo all additions of the submodules?

2024-12-20 10:33 UTC, hverhelst commented on src/gsAssembler/gsExprHelper.h
Can you undo these changes and check if we need them?

2024-12-20 10:33 UTC, hverhelst commented on src/gsCore/gsBasis.h
Undo this

2024-12-20 10:33 UTC, hverhelst commented on src/gsCore/gsBasis.hpp
Please undo this

2024-12-20 10:33 UTC, hverhelst commented on src/gsCore/gsRationalBasis.h
> +    index_t size(index_t const& k) const{ return m_src->size(k); }
Maybe use the types from here:
https://github.com/gismo/gismo/blob/3fa0f13f5aadd03170c8229e41640ab084d11043/src/gsTensor/gsTensorBasis.h#L437C7-L437C65

2024-12-20 10:33 UTC, hverhelst commented on src/gsCore/gsRationalBasis.h
> +    void refine(gsMatrix<T> const & boxes, int refExt = 0)
Remove this whole part (including docs) since it does not implement

2024-12-26 06:20 UTC, Crazy-Rich-Meghan commented
Hi @hverhelst, Thank you for the review! I’m currently in vacation mode, so I took my time to complete the revisions. After this PR, we should be able to run preCICE with stable branch :)

2024-12-27 09:23 UTC, hverhelst approved these changes

2024-12-27 09:24 UTC, hverhelst approved these changes

2025-01-03 09:22 UTC, filiatra approved these changes

2025-01-03 09:23 UTC, merged